### ISSUE TITLE
How to receive events?

### ISSUE THREAD

**Issue by Jack-Works** [MetaMask/extension-provider#11]
```js
ethereum.on('accountsChanged', handler: (accounts: Array<string>) => void);
```

https://docs.metamask.io/guide/ethereum-provider.html#accountschanged

But there is no `ethereum` object injected by MetaMask in the extension environment, how can I receive this kind of event?

**Comment by Tedko** [comment]
@danfinlay Many thx

**Comment by danfinlay** [comment]
Were you able to figure this out? Per the readme, you should be able to subscribe to events by constructing an `ethereum` provider like this:
```
const createMetaMaskProvider = require('metamask-extension-provider')

const provider = createMetaMaskProvider()

provider.on('error', (error) => {
  // Failed to connect to MetaMask, fallback logic.
})
```

**Comment by tong0x** [comment]
Hi, I am trying to use the event listener "accountsChanged" as @danfinlay mentioned, but I'm not able to receive any events. I am subscribing to events by constructing an Ethereum provider like above in the frontend portion of my extension. Would you have any clue as to why the event might not be firing?

**Comment by tong0x** [comment]
Main goal of this is to ensure my own extension is updated to using the currently selected account address on Metamask
