### ISSUE TITLE
How to declare who am I in the MetaMask?

### ISSUE THREAD

**Issue by Jack-Works** [MetaMask/extension-provider#12]
![image](https://user-images.githubusercontent.com/5390719/91808483-1cf3a800-ec5f-11ea-89c4-5b6c723791bb.png)

Now our extension is displayed as "External Extension" with no logo in the MetaMask. How can I specify a name and a logo?

**Comment by danfinlay** [comment]
Currently an extension receiving events from another extension only gets the extension ID, so to improve this we would need to perform a lookup on the extension store by the current browser to get extension metadata.
