### ISSUE TITLE
How to know if Metamask is already installed?

### ISSUE THREAD

**Issue by Jack-Works** [MetaMask/extension-provider#9]

**Comment by Tedko** [comment]
![Clipboard - 2020年8月18日下午4点53分](https://user-images.githubusercontent.com/6687437/90493679-3d0e6c00-e175-11ea-8333-00d952176570.png)
Right now finished the integration. however within our extension we have no idea whether user install MetaMask already or not.
@danfinlay  any good idea? Many thanks

**Comment by brad-decker** [comment]
I would recommend using our [onboarding library](https://github.com/MetaMask/metamask-onboarding) for these purposes. Examples can be seen [here](https://docs.metamask.io/guide/onboarding-library.html#examples)

**Comment by Tedko** [comment]
Hi @brad-decker .

We already noticed onboarding library. However Metamask cannot inject js into another extension's page ( something like chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/index.html#/wallets )

That's why we're wondering if there's any solution.

**Comment by Tedko** [comment]
injecting js into another extension's page is not allowed by browser. There're other browser APIs could do so (some communication between extensions)

Right now we already able to use MetaMask inside Maskbook extension, and then provide MetaMask func on fb/Twitter. The only problem is within the extension's html page we don't know whether users installed Maskbook or not

**Comment by Jack-Works** [comment]
I'm afraid the onboarding library doesn't work for another web extension.

https://github.com/MetaMask/metamask-onboarding/blob/master/src/index.ts#L154

In this line, you detect metamask by `window.ethereum.isMetaMask` but `window.ethereum` is not available in the web extension. This is why I'm using `extension-provider`\`(this library)

**Comment by Tedko** [comment]
Hi @brad-decker  - any thoughts?

**Comment by neruthes** [comment]
I have been wondering whether this way is going to work.

If MetaMask is installed:

- The user clicks "Link a MetaMask Wallet" button.
- Maskbook opens URL "https://maskbook.com/webext-bridge/metamask.html" in a new tab.
- MetaMask injects some object on `window`.
- Maskbook reads the injected object on `window`.
- Maskbook knows that MetaMask is installed.
- Maskbook sends requests to MetaMask through the webpage.

If MetaMask is not installed:

- (Shared initial steps)
- Maskbook fails reading the injected object on `window`.
- Maskbook lets the webpage know the failure.
- The webpage suggests the user to install MetaMask with a proper browser-specific extension store link.

**Comment by danfinlay** [comment]
You should also be able to detect whether MetaMask is installed using the `error` event we have on this library's provider:

```
const createMetaMaskProvider = require('metamask-extension-provider')

const provider = createMetaMaskProvider()

provider.on('error', (error) => {
  // Failed to connect to MetaMask, likely MetaMask is not installed.
})
```

**Comment by Tedko** [comment]
@danfinlay thx it seems working well now :) @Jack-Works  should we close this? would be great if you can make a document of this @danfinlay

**Comment by Jack-Works** [comment]
Yeah I think we can close this now

**Comment by Tedko** [comment]
🎭 Thx for all 🦊❤️
